server:
  port: 8088
  undertow:
    decode-url:
spring:
  datasource:
     datasource1:
        url: jdbc:mysql://localhost:3306/datasource1?useUnicode=true&characterEncoding=utf-8
        username: root
        password: 123456
        driverClassName: com.mysql.jdbc.Driver
     datasource2:
        url: jdbc:mysql://localhost:3306/datasource2?useUnicode=true&characterEncoding=utf-8
        username: root
        password: 123456
        driverClassName: com.mysql.jdbc.Driver
mybatis:
  mapper-locations: classpath:com/leetcode/demo/page/mapper/*Mapper.xml

